### ISSUE TITLE
Some transcoded characters contains ":" which caused incorrect display

### ISSUE THREAD

**Issue by ShekPS** [matanki-saito/EU4SpecialEscape#9]
In the estate modifier message, paradox will delete the §Y$VAL$%§! part according to the position of ":".
In this case, 「区」 contains a ":" after transcode, so the message after it becomes incorrect.
![default](https://user-images.githubusercontent.com/26006407/53804894-aa2f4100-3f83-11e9-94cf-d8f436084650.png)
![default](https://user-images.githubusercontent.com/26006407/53804942-d054e100-3f83-11e9-9c92-e8124b547e53.png)

related localisation: ESTATEMOD_LOST_*, EST_VAL_JAINS_DECLINE

**Comment by matanki-saito** [comment]
Thank you. I check it.
